defaults:
  - model: bert_large_uncased
  - paths: boolq
  - training: boolq
  - query_generation: qa
  - runtime: gpu
  - _self_

seed: 42

run:
  scheme: random
  step: all

model:
  max_seq_length: 512

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
