defaults:
  - model: bert_large_uncased
  - paths: classifier
  - training: classifier
  - query_generation: classifier
  - runtime: gpu
  - _self_

seed: 42

run:
  task: SST-2
  scheme: random
  step: all

model:
  max_seq_length: 128

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
